Repetitions : src/Repetitions.cpp
	g++ -o Repetitions src/Repetitions.cpp -std=c++11 -Wall
Increasing_Ar : src/Increasing_Ar.cpp
	g++ -o Increasing_Ar src/Increasing_Ar.cpp -std=c++11 -Wall
Permutations : src/Permutations.cpp
	g++ -o Permutations src/Permutations.cpp -std=c++11 -Wall
clean:
	rm Repetitions Increasing_Ar Permutations
