dice_combo : src/dice_combo.cpp
	g++ -o dice_combo src/dice_combo.cpp -std=c++11 -Wall
min_coin : src/min_coin.cpp
	g++ -o min_coin src/min_coin.cpp -std=c++11 -Wall
coin_combo1 : src/coin_combo1.cpp
	g++ -o coin_combo1 src/coin_combo1.cpp -std=c++11 -Wall
coin_combo2 : src/coin_combo2.cpp
	g++ -o coin_combo2 src/coin_combo2.cpp -std=c++11 -Wall
rem_dig : src/rem_dig.cpp
	g++ -o rem_dig src/rem_dig.cpp -std=c++11 -Wall
grid_paths : src/grid_paths.cpp
	g++ -o grid_paths src/grid_paths.cpp -std=c++11 -Wall
book_shop : src/book_shop.cpp
	g++ -o book_shop src/book_shop.cpp -std=c++11 -Wall
ar_desc : src/ar_desc.cpp
	g++ -o ar_desc src/ar_desc.cpp -std=c++11 -Wall
projects : src/projects.cpp
	g++ -o projects src/projects.cpp -std=c++11 -Wall
clean:
	rm dice_combo min_coin coin_combo1 coin_combo2 rem_dig grid_paths book_shop ar_desc projects
